export const techData = [
    {
        name:"HTML5",
        icon:"./html.svg"
    },
    {
        name:"CSS3",
        icon:"./css.svg"
    },
    {
        name:"Tailwind CSS",
        icon:"./tailwind.svg"
    },
    {
        name:"JavaScript",
        icon:"./javascript.svg"
    },
    {
        name:"React",
        icon:"./react.svg"
    },
    {
        name:"Node JS",
        icon:"./nodejs.svg"
    },
    {
        name:"Express JS",
        icon:"./express.svg"
    },
    {
        name:"MongoDB",
        icon:"./mongoDB.svg"
    },
    {
        name:"Firebase",
        icon:"./firebase.svg"
    },
    {
        name:"Next JS",
        icon:"./nextjs.svg"
    },
    {
        name:"Three JS",
        icon:"./threejs.svg"
    },
    {
        name:"GreenSock",
        icon:"./greenSock.svg"
    },
    {
        name:"Docker",
        icon:"./docker.svg"
    },
    {
        name:"Git",
        icon:"./git.svg"
    },
    {
        name:"Blender",
        icon:"./blender.svg"
    },
    {
        name:"C++",
        icon:"./cplus.svg"
    },
    {
        name:"Figma",
        icon:"./figma.svg"
    },
    {
        name:"webGL",
        icon:"./webGL.svg"
    },
]